
twilio:
  account_sid: ACa5e1fb3bfe3d079ef48e553685d98d88
  auth_token: abd44b40551e66702b08f76d111eb485
  trial_number: +12059973730
amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAIJOFWP66LVSY5MXQ
  secretKey: 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
  bucketName: vedikaas
  
 